version: '3.9'

x-coolify:  # Esta é uma extensão YAML para configurações do Coolify (deve estar no nível raiz)
  domain: mrfinancas.burghausen.com.br
  services:
    node:
      domain: mrfinancas.burghausen.com.br
      port: 4081
    

services:

    node:
    image: marcosrafaelburghausen/node-19
    container_name: Mr_frontend
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    command: bash -c "npm i && npm run dev -- --host"
    networks:
      - network
    ports:
      - "4081:5173"
    volumes:
      - "./frontend:/home/node/app"
      - "/data/coolify/source/financas/frontend:/home/node/app:cached"
    environment:
      # VITE_BACK_HOST: "http://api.mrfinancas.burghausen.com.br"
      BACK_HOST: php:4081/api
      CHOKIDAR_USEPOLLING: 'true'

 


volumes:
  mysql_db:
    driver: "local"
  redis_db:
    driver: "local"

networks:
  network:
    driver: bridge
