# frontend/nginx.conf

server {
    listen 80;
    server_name localhost;

    # Define a pasta raiz onde estão os arquivos do site
    root /usr/share/nginx/html;
    index index.html;

    # Configuração crucial para SPAs (Single Page Applications)
    # Tenta encontrar o arquivo solicitado. Se não encontrar,
    # ele serve o index.html para que o Vue Router possa assumir a rota.
    location / {
        try_files $uri $uri/ /index.html;
    }
}