version: '3.8'

services:
  #php+apache
  backend_dev: # <-- MUDANÇA: Nome do serviço
    image: marcosrafaelburghausen/php8.3-apache2.4
    container_name: Mr_backend_dev # <-- MUDANÇA: Nome do container
    working_dir: /var/www/html/
    depends_on:
      - mysql_dev
      - redis_dev
    networks:
      - network_dev # <-- MUDANÇA: Nome da rede
    ports:
      - "4080:80" # Porta para o backend
    volumes:
      - "./backend:/var/www/html"

  #node
  frontend_dev: # <-- MUDANÇA: Nome do serviço
    image: marcosrafaelburghausen/node-19
    container_name: Mr_frontend_dev # <-- MUDANÇA: Nome do container
    working_dir: /home/node/app
    command: bash -c "npm i && npm run dev -- --host"
    networks:
      - network_dev # <-- MUDANÇA: Nome da rede
    ports:
      - "4081:5173" # Porta para o frontend
    volumes:
      - "./frontend:/home/node/app"
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  #mysql
  mysql_dev: # <-- MUDANÇA: Nome do serviço
    image: mysql:8.0
    container_name: Mr_database_dev # <-- MUDANÇA: Nome do container
    networks:
      - network_dev # <-- MUDANÇA: Nome da rede
    ports:
      - "3306:3306" # Expor a porta do MySQL é ok para DEV, mas removeremos em PROD
    volumes:
      - "./db:/home/bkp"
      - "mysql_db_dev:/var/lib/mysql" # <-- MUDANÇA: Volume de dados separado
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      MYSQL_DATABASE: Mr_database_dev # <-- MUDANÇA: Nome do banco DEV

  #phpmyadmin
  dbadmin_dev: # <-- MUDANÇA: Nome do serviço
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_dev # <-- MUDANÇA: Nome do container
    restart: "no"
    networks:
      - network_dev # <-- MUDANÇA: Nome da rede
    ports:
      - "4033:80" # Porta para o phpMyAdmin
    environment:
      PMA_HOST: mysql_dev # <-- MUDANÇA: Aponta para o DB de dev
      PMA_PORT: 3306

  #redis
  redis_dev: # <-- MUDANÇA: Nome do serviço
    image: redis:7.0
    container_name: Mr_session_database_dev # <-- MUDANÇA: Nome do container
    command: bash -c "redis-server --requirepass senha"
    networks:
      - network_dev # <-- MUDANÇA: Nome da rede
    ports:
      - "6379:6379" # Expor a porta do Redis é ok para DEV, mas removeremos em PROD
    volumes:
      - "redis_db_dev:/data" # <-- MUDANÇA: Volume de dados separado

  #redis-commander
  redis_commander_dev: # <-- MUDANÇA: Nome do serviço
    image: rediscommander/redis-commander:latest
    container_name: redis-commander_dev # <-- MUDANÇA: Nome do container
    restart: always
    environment:
      - REDIS_HOST=redis_dev # <-- MUDANÇA: Aponta para o Redis de dev
      - REDIS_PORT=6379
      - REDIS_PASSWORD=senha
    ports:
      - "8082:8081" # Porta para o Redis Commander
    networks:
      - network_dev # <-- MUDANÇA: Nome da rede

volumes:
  mysql_db_dev: # <-- MUDANÇA
    driver: "local"
  redis_db_dev: # <-- MUDANÇA
    driver: "local"

networks:
  network_dev: # <-- MUDANÇA
    driver: bridge
