version: '3.9'

services:
  frontend:
    image: marcosrafaelburghausen/node-19
    container_name: Mr_frontend
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    command: bash -c "npm i && npm run dev -- --host"
    networks:
      - network
    ports:
      - "4081:5173"
    volumes:
      - "./frontend:/home/node/app"
    environment:
      BACK_HOST: php:4081/api
      CHOKIDAR_USEPOLLING: 'true'


networks:
  network:
    driver: bridge