version: '3.9'

services:

  #php+apache
  php:
    build:
      dockerfile: ../docker/php.Dockerfile
      context: ./backend
    container_name: Mr_backend
    working_dir: /var/www/html/
    depends_on:
      - mysql
      - redis
    networks:
      - network
    ports:
      - "4090:80"
    volumes:
      - "./backend:/var/www/html"
      - "./apache/sites-enabled/:/etc/apache2/sites-enabled/"
    environment:
      FRONTEND_HOST: node:4080
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      MYSQL_DATABASE: Mr_database
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: senha

  #node
  node:
    build:
      dockerfile: ../docker/node.build.Dockerfile
      context: ./frontend
    container_name: Mr_frontend
    networks:
      - network
    ports:
      - "4081:80"

  #mysql
  mysql:
    image: mysql:8.0
    container_name: Mr_database
    networks:
      - network
    ports:
      - "3306:3306"
    volumes:
      - "./db:/home/bkp"
      - "mysql_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      MYSQL_DATABASE: Mr_database
      #mysql://mysql:vhT6kKVvSLLl47vJJl1N6p0wnRHdW5rZwyzA7vGvzrTutcQFN3DC3WDhNgFy1dDw@bosg48w88wcwkko00owgswsg:3306/default

  #redis
  redis:
    image: redis:7.0
    container_name: Mr_session_database
    command: bash -c "redis-server --requirepass senha"
    networks:
      - network
    ports:
      - "6379:6379"
    volumes:
      - "redis_db:/data"
      # redis://default:QMV7QdQrFHJ0jfqLbv3ukEKl4QKKb1D4edGayF0pDxoqMwa4i1cddioCyhPlE9U0@h8co0kk0w08kk0og488cgkg0:6379/0

volumes:
  mysql_db:
    driver: "local"
  redis_db:
    driver: "local"

networks:
  network:
    driver: bridge
