name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Hetzner to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 128.140.67.177 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no root@128.140.67.177 'echo "SSH connection successful"'

      - name: Clean and Update Server
        run: |
          ssh -o StrictHostKeyChecking=no root@128.140.67.177 << 'EOF'
            cd /root/Financas
            git pull origin main && docker compose down && docker compose -f docker-compose-prod.yml up -d --build
          EOF

      - name: Run Laravel Queue Worker
        run: |
          ssh -T -o StrictHostKeyChecking=no root@128.140.67.177 << 'EOF'
            cd /root/Financas
            docker exec Mr_backend php artisan queue:work
          EOF
