name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Hetzner to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 128.140.67.177 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no root@128.140.67.177 'echo "SSH connection successful"'

      - name: Copy files via SCP
        run: scp -o StrictHostKeyChecking=no -r ./* root@128.140.67.177:/root/Financas

      - name: Run SSH commands
        run: ssh -o StrictHostKeyChecking=no root@128.140.67.177 'cd /root/Financas && git pull origin main'
